export const DEFAULT_PAGES = {
  privacy: {
    pageTitle: 'Privacy Policy',
    sections: [
      {
        heading: 'Overview',
        body: 'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\n\nWe use Your Personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.',
        order: 0
      },
      {
        heading: 'Interpretation & Definitions',
        body: 'The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.\n\nAccount: means a unique account created for You to access our Service or parts of our Service.\n\nCompany: refers to STAT Surgical Supplies, 9/330, Nethaji Street, Karnan Nagar, Polichalur, Chennai 600074.\n\nCookies: are small files that are placed on Your computer, mobile device or any other device by a website.\n\nCountry: refers to: Tamil Nadu, India\n\nDevice: means any device that can access the Service.\n\nPersonal Data: is any information that relates to an identified or identifiable individual.\n\nService: refers to the Website.\n\nService Provider: means any natural or legal person who processes the data on behalf of the Company.\n\nUsage Data: refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.\n\nWebsite: refers to STAT Surgical Supplies, accessible from https://www.statsurgicals.com/\n\nYou: means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
        order: 1
      },
      {
        heading: 'Collecting and Using Your Personal Data',
        body: 'While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n- Email address\n- First name and last name\n- Phone number\n- Address, State, Province, ZIP/Postal code, City\n\nUsage Data is collected automatically when using the Service. Usage Data may include information such as Your Device\'s Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.',
        order: 2
      },
      {
        heading: 'Tracking Technologies and Cookies',
        body: 'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.\n\nCookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.\n\nNecessary / Essential Cookies (Session Cookies): These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.\n\nCookies Policy / Notice Acceptance Cookies (Persistent Cookies): These Cookies identify if users have accepted the use of cookies on the Website.\n\nFunctionality Cookies (Persistent Cookies): These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.',
        order: 3
      },
      {
        heading: 'Use of Your Personal Data',
        body: 'The Company may use Personal Data for the following purposes:\n- Service Maintenance: To provide and maintain our Service, including to monitor the usage of our Service.\n- Account Management: To manage Your Account registration.\n- Contractual Performance: The development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.\n- Communication Protocols: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.\n- Offers & Updates: To provide You with news, special offers and general information about other goods, services and events.\n- Request Management: To attend and manage Your requests to Us.\n- Business Transfers: To evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer.\n- Data Analytics: For data analysis, identifying usage trends, and to evaluate and improve our Service.',
        order: 4
      },
      {
        heading: 'Retention & Transfer of Your Personal Data',
        body: 'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.\n\nYour information, including Personal Data, is processed at the Company\'s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.',
        order: 5
      },
      {
        heading: 'Disclosure & Security of Your Personal Data',
        body: 'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.\n\nUnder certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.\n\nThe security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
        order: 6
      },
      {
        heading: 'Children\'s Privacy & Links',
        body: 'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.\n\nOur Service may contain links to other websites that are not operated by Us. If You click on a third party link, you will be directed to that third party\'s site. We strongly advise You to review the Privacy Policy of every site You visit.',
        order: 7
      },
      {
        heading: 'Contact Us',
        body: 'If you have any questions about this Privacy Policy, you can contact us:\n- Email Inquiry: statsurgicalsupplies@gmail.com\n- Corporate Office: Chennai, Tamil Nadu, India',
        order: 8
      }
    ]
  },
  terms: {
    pageTitle: 'Terms & Conditions',
    sections: [
      {
        heading: 'Overview',
        body: 'This document governs the use of our website, and any other related agreement or legal relationship with us in a legally binding way. You must read this document carefully.\n\nBy using our website, you agree to these Terms & Conditions. If you do not agree to all terms, please refrain from using the service.',
        order: 0
      },
      {
        heading: 'About Us',
        body: 'Company Name: STAT Surgical Supplies\nProprietor: Mrs. Shanmuga Priya\nAddress: 9/330, Nethaji Street, Karnan Nagar, Polichalur, Chennai 600074, Tamil Nadu, India\nEmail Contact: statsurgicalsupplies@gmail.com',
        order: 1
      },
      {
        heading: 'Terms of Use',
        body: 'Unless stated otherwise, the terms in this section apply generally when using our website.\n\nBy using our website, you confirm the following:\n1. You are older than 18 years of age.\n2. You are not in a country under the Indian Government embargo.',
        order: 2
      },
      {
        heading: 'Liability & Indemnity',
        body: 'We limit our liability as much as legally allowed when executing agreements with you. This means our responsibility for damages is reduced to the maximum extent permitted by law.\n\nYou agree to indemnify us and our affiliates, officers, directors, and employees from any claims or demands made by third parties due to or in connection with any culpable violation of these terms or third-party rights.',
        order: 3
      },
      {
        heading: 'Disclaimers',
        body: 'Our website is provided on an "as is" and "as available" basis. When you use our service, you are doing so at your own risk. We explicitly state that we are not making any promises or guarantees, whether they are express, implied, or even required by law.\n\nAdditionally, while we strive to provide accurate and reliable content, we cannot guarantee that the service will always meet your requirements or be available when you need it.',
        order: 4
      },
      {
        heading: 'Common Provisions',
        body: 'No Waiver: Our failure to assert any right or provision under these terms does not waive that right or provision.\n\nService Interruption: We reserve the right to interrupt the service for maintenance, updates, or other changes, with appropriate notification.\n\nIntellectual Property: All intellectual property rights associated with our website remain our exclusive property.\n\nGoverning Law & Jurisdiction: These terms are governed by the law of Chennai, Tamil Nadu, India. The jurisdiction over any controversy lies exclusively with the courts of Chennai.',
        order: 5
      },
      {
        heading: 'Surviving Provisions',
        body: 'Upon termination, the provisions contained in this document that by their context are intended to survive termination will survive, including license grants, indemnification obligations, and disclaimer of warranties.',
        order: 6
      }
    ]
  },
  shipping: {
    pageTitle: 'Shipping Policy',
    sections: [
      {
        heading: '[Method] Standard Shipping',
        body: '3-5 business days | Affordable delivery for standard orders across regional routes.',
        order: 0
      },
      {
        heading: '[Method] Express Shipping',
        body: '1-2 business days | Fast-tracked air dispatch for time-sensitive tools and orders.',
        order: 1
      },
      {
        heading: '[Method] Same-Day Delivery',
        body: 'select areas only | Immediate dispatch for urgent local needs within eligible zones.',
        order: 2
      },
      {
        heading: '[Info] Processing Time',
        body: 'Orders are typically processed within 24 hours of being placed. During peak seasons or promotional periods, processing may take up to 48 hours.',
        order: 3
      },
      {
        heading: '[Info] International Shipping',
        body: 'We ship to over 100 countries worldwide. International shipping typically takes 7-14 business days, depending on the destination and customs processing.',
        order: 4
      },
      {
        heading: '[Info] Shipping Costs',
        body: 'Shipping costs are calculated based on weight, dimensions, and destination. Free shipping is available for bulk/qualifying institutional orders.',
        order: 5
      },
      {
        heading: '[FAQ] How can I track my order?',
        body: 'Once your order ships, you\'ll receive a tracking number via email. You can also track your order in your account dashboard under "Order History."',
        order: 6
      },
      {
        heading: '[FAQ] What if my package is lost or damaged?',
        body: 'If your package is lost or damaged during transit, please contact our customer service team immediately so we can assist you with a replacement or refund.',
        order: 7
      },
      {
        heading: '[FAQ] Do you ship to P.O. boxes?',
        body: 'Yes, standard shipping supports deliveries to P.O. boxes. Express and same-day dispatches require a physical, verified shipping address.',
        order: 8
      }
    ]
  },
  returns: {
    pageTitle: 'Returns & Refunds',
    sections: [
      {
        heading: '[Step] Step 1: Initiate',
        body: 'Online Request | Log in to your account, go to "Order History", select the order and click "Return Items" to start.',
        order: 0
      },
      {
        heading: '[Step] Step 2: Label & Pack',
        body: 'Prepaid Label | Print the prepaid return shipping label. Package the item(s) securely and attach the label.',
        order: 1
      },
      {
        heading: '[Step] Step 3: Drop Off',
        body: 'Authorized Hub | Drop off the package at any authorized shipping location.',
        order: 2
      },
      {
        heading: '[Info] Return Policy',
        body: 'We accept returns within 30 days of purchase for most items. Products must be in original condition with all packaging and tags intact.\n- Personalized or custom-made products\n- Sterile clinical packages once opened\n- Lifesaving equipment after seal breach\n- Defective items must be reported within 48 hours',
        order: 3
      },
      {
        heading: '[Info] Processing Time',
        body: 'Return processing typically takes 3-5 business days from the time we receive your item. Refunds are usually processed within 7-10 business days, depending on your payment method.',
        order: 4
      },
      {
        heading: '[Info] Refund Methods',
        body: 'Refunds will be issued to the original payment method used for the purchase. For credit card payments, it may take an additional 3-5 business days for the refund to appear on your statement. You may also choose to receive store credit, which will be issued immediately upon approval.',
        order: 5
      },
      {
        heading: '[FAQ] What if I received a defective item?',
        body: 'If you receive a defective item, please contact our customer service team within 48 hours of delivery. We\'ll arrange for a replacement or refund at no additional cost to you.',
        order: 6
      },
      {
        heading: '[FAQ] Do I have to pay for return shipping?',
        body: 'Return shipping is free for defective items or if we sent the wrong product. For other returns, a shipping flat fee will be deducted from your refund to cover return shipping costs.',
        order: 7
      }
    ]
  },
  faq: {
    pageTitle: 'FAQ',
    sections: [
      {
        heading: '[Orders & Shipping] How long does shipping take within India?',
        body: 'Most orders are processed within 24-48 hours. Delivery takes 3-5 business days for major cities and 5-7 business days for regional clinics and hospitals across India.',
        order: 0
      },
      {
        heading: '[Orders & Shipping] Do you offer express delivery for urgent surgical supplies?',
        body: 'Yes, express overnight shipping is available for select items to hospitals and clinics across major metros. Please contact support via WhatsApp or call to request express dispatch.',
        order: 1
      },
      {
        heading: '[Orders & Shipping] How can I track my bulk order?',
        body: 'Once shipped, a tracking number and link from our shipping partners (Delhivery, BlueDart, DTDC) will be sent to your registered email and WhatsApp.',
        order: 2
      },
      {
        heading: '[Returns & Refunds] What is your return policy on medical/surgical equipment?',
        body: 'Due to sterility and safety standards, returns are accepted within 7 days of delivery only for unused, unopened items in their original packaging. Lifesaving and sterilized items are not returnable once opened.',
        order: 3
      },
      {
        heading: '[Returns & Refunds] How do I initiate a refund or exchange?',
        body: 'To request a return/refund, email statsurgicalsupplies@gmail.com with your order number and invoice. Our quality control team will inspect the item before approval.',
        order: 4
      },
      {
        heading: '[Products & Inventory] Are all STAT Surgical products certified and quality tested?',
        body: 'Absolutely. All products are CE/ISO certified and undergo strict multi-point inspections before dispatch to ensure clinical compliance.',
        order: 5
      },
      {
        heading: '[Products & Inventory] Do you provide warranty and servicing for diagnostic devices?',
        body: 'Yes, diagnostic devices like ECG monitors and pulse oximeters come with a 1-year manufacturer warranty. We also provide post-purchase calibration support.',
        order: 6
      },
      {
        heading: '[Account & Payment] What payment methods do you accept?',
        body: 'We accept all major credit/debit cards, UPI (Google Pay, PhonePe, Paytm), Net Banking (SBI, HDFC, ICICI), Razorpay, and direct Bank Transfer (RTGS/NEFT) for institutional bulk orders.',
        order: 7
      },
      {
        heading: '[Account & Payment] Is my payment information secure?',
        body: 'Yes, all transactions are processed through secure, PCI-DSS compliant payment gateways (Razorpay) utilizing 256-bit SSL encryption.',
        order: 8
      }
    ]
  }
};
